---
# Source: weaviate/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weaviate
spec:
  progressDeadlineSeconds: 1200
  selector:
    matchLabels:
      app.kubernetes.io/name: weaviate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: weaviate
    spec:
      containers:
        - name: weaviate
          image: 'docker.io/semitechnologies/weaviate:0.22.7'
          ports:
            - containerPort: 8080
          args:
            - '--host'
            - '0.0.0.0'
            - '--port'
            - '8080'
            - '--scheme'
            - 'http'
            - '--config-file'
            - '/weaviate-config/conf.yaml'
          volumeMounts:
            - name: weaviate-config
              mountPath: /weaviate-config
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 200Mi
      volumes:
        - name: weaviate-config
          configMap:
            name: weaviate-config
