# Source: weaviate/charts/etcd/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2379
      targetPort: client
    - name: peer
      port: 2380
      targetPort: peer
  selector:
    app.kubernetes.io/name: etcd
